# Generated by Django 3.1 on 2020-12-11 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('orders', '0001_initial'), ('orders', '0002_order_duration'), ('orders', '0003_auto_20200409_1156'), ('orders', '0004_auto_20200409_1330'), ('orders', '0005_auto_20200421_2137'), ('orders', '0006_auto_20200421_2139'), ('orders', '0007_auto_20200421_2303'), ('orders', '0008_order_state'), ('orders', '0009_auto_20200423_1007'), ('orders', '0010_auto_20200423_1010'), ('orders', '0011_auto_20200423_1022'), ('orders', '0012_order_date_start')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('customers', '0002_auto_20200421_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_pickup', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.fields.Empty, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('duration', models.DurationField(default=datetime.timedelta(1))),
                ('state', models.CharField(choices=[('Open', 'Open'), ('Started', 'Started'), ('Finished', 'Finished')], default='Open', max_length=10)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
